api/v1_tracks_trending_underground.go
api/v1_tracks_trending_underground_test.go

Corresp audius-protocol PR:
https://github.com/AudiusProject/audius-protocol/pull/12566

[API-277] Only skip top 20 trending in underground trending

---

api/v1_metrics_apps.go

- Bad max limit
- Parsed params wrong

Fix app metrics queries

---

api/server.go
api/v1_users_authorized_apps.go
api/v1_users_authorized_apps_test.go
solana/indexer/balance_changes.go

Just bridge be doing bridge things

Add authorized apps

---

api/server.go
api/swagger/swagger-v1.yaml
api/v1_users_verify_token.go
api/v1_users_verify_token_test.go

Bridge doing bridge things
http://localhost:1323/v1/users/verify_token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJrZWNjYWsyNTYifQ.eyJ1c2VySWQiOiJZb3g3bE1KIiwiZW1haWwiOiJyYXkrNzI0MjVAYXVkaXVzLmNvIiwibmFtZSI6InJheTcyNDI1IiwiaGFuZGxlIjoicmF5NzI0MjUiLCJ2ZXJpZmllZCI6ZmFsc2UsInByb2ZpbGVQaWN0dXJlIjp7IjE1MHgxNTAiOiJodHRwczovL2Jsb2NrZGFlbW9uLWF1ZGl1cy1jb250ZW50LTA1LmJkbm9kZXMubmV0L2NvbnRlbnQvMDFLMFlRUDNCVkJKWDRXUzQ3SzFFWjhHVjgvMTUweDE1MC5qcGciLCI0ODB4NDgwIjoiaHR0cHM6Ly9ibG9ja2RhZW1vbi1hdWRpdXMtY29udGVudC0wNS5iZG5vZGVzLm5ldC9jb250ZW50LzAxSzBZUVAzQlZCSlg0V1M0N0sxRVo4R1Y4LzQ4MHg0ODAuanBnIiwiMTAwMHgxMDAwIjoiaHR0cHM6Ly9ibG9ja2RhZW1vbi1hdWRpdXMtY29udGVudC0wNS5iZG5vZGVzLm5ldC9jb250ZW50LzAxSzBZUVAzQlZCSlg0V1M0N0sxRVo4R1Y4LzEwMDB4MTAwMC5qcGciLCJtaXJyb3JzIjpbImh0dHBzOi8vYXVkaXVzLWNvbnRlbnQtMS5maWdtZW50LmlvIiwiaHR0cHM6 …

Implement users/verify_token

---

logging/logger.go
solana/indexer/solana_indexer.go
solana/indexer/subscription.go

Report SolanaIndexer logs to Axiom on 15s interval

---

api/server.go
api/v1_users_sales_aggregate.go
api/v1_users_sales_aggregate_test.go

Had to manually construct a diff for staging b/c I had no sales :)
Only diff is hashing ids, which we dont use in the client anywhere

[API-225] Add v1/users/:userId/sales/aggregate

---

api/swagger/swagger-v1.yaml

Fix owner_id on /coins endpoint

---

ddl/functions/chat_blast_audience.sql

Got a bit trigger happy in #282

Add missing semicolon to function

---

api/swagger/swagger-v1.yaml

After seeing the SDK types, decided to change the names a bit

Touch up the swagger for better auto generated SDK types

---

solana/indexer/unprocessed_transactions.go

Forgot to push this commit before merging to keep logs to a minimum

Missed commit from deadletter queue

---

api/comms_chats_messages.go
api/comms_chats_messages_test.go
database/seed.go

The chat blast special-case was not implemented during the migration to api, this adds it back.
Untested, will test on stage.

Fix sender-side chat blasts

---

api/dbv1/get_tracks.sql.go
api/dbv1/queries/get_tracks.sql
api/swagger/swagger-v1-full.yaml
api/v1_tracks_most_shared.go
api/v1_users_recommended_tracks.go
database/seed.go
indexer/index_track.go

This reverts commit 3a8acef5b37a19b4bc12125f01e5a8cc12e2c77a.

Revert "[API-306] Filter deactivated tracks on recommended (#314)"

---

.github/workflows/build.yml
Dockerfile

Builds the image compatible with our Macbooks

Add ARM64 target platform for docker image

---

.github/workflows/build.yml

Accidentally left some debugging echos in instead of actually calling the docker command.

Remove echos used for debugging

---

api/comms_blasts.go
api/comms_blasts_test.go
database/seed.go

Also adds new test file for chat blasts.

Add timing checks to getNewBlasts

---

api/v1_notifications.go

FE needs: https://github.com/AudiusProject/audius-protocol/pull/12748

Disable remix notif

---

api/v1_create_coin.go
api/v1_create_coin_test.go

User's should only be able to create one artist coin. Added a check to enforce this.

Update to only allow user to create one coin

---

api/server.go
api/v1_users_purchasers_count.go
api/v1_users_purchasers_count_test.go

Another missed count endpoint.

[API-315] Migrate `/v1/full/users/:id/purchasers/count`

---

api/dbv1/access.go
api/dbv1/jsonb_access_gate.go
api/swagger/swagger-v1-full.yaml
api/swagger/swagger-v1.yaml
api/v1_track_access_info.go

Small updates to add support for token gating and updated the swagger docs

[PE-6806] Add support for token gating

---

ddl/functions/is_country_eur.sql

https://github.com/AudiusProject/audius-protocol/pull/12873/files

Remove US, MX from is_country_eur

---

api/dbv1/get_users.sql.go
api/dbv1/queries/get_users.sql
api/server_test.go
api/testdata/artist_coins_fixtures.go
api/v1_users_test.go

Adds ticker to artist_coin_badge to prevent coin endpoint fetches needed for artist-coin-hover-card.
Adds artist_coin_badge check in user test

Add ticker to artist_coin_badge

---

api/swagger/swagger-v1-full.yaml

Add ticker to swagger

---

api/server.go

Add ip to fields

---

ddl/functions/chat_blast_audience.sql

If you send a blast to remixers of a track and you are one of those remixers, it will fan out to every DM you have. 😬

don't include self-remixes in remix blast audience

---

api/comms/chat.go
api/comms/chat_blast_test.go
ddl/functions/chat_blast_audience.sql

- incorporate artist coin decimals into audience calculation
- add a test that user 209 who holds less than 1 full coin doesn't receive blast

[PE-7000] Require 1 artist coin to receive blast

---

api/v1_create_coin.go
api/v1_create_coin_test.go

Undo launchpad coin is verified check (again for QA reasons)

---

jobs/coin_dbc.go

Planning to use this to help choose the correct 3rd party wallet for fee claiming (since it has to be the same wallet)

Add creator wallet to pool dbc config

---

config/solana_config.go
jobs/coin_dbc.go
solana/indexer/solana_indexer.go
solana/indexer/subscription.go

This change will allow us to get realtime price updates on our DBC pools, hopefully solving the $0 price problem on coin launch w/ first buy.

Listen for DBC account changes in solana indexer

---

api/v1_coin_insights.go
api/v1_coins.go

I added this to the pools table, adding it to endpoints now

Add creator wallet to coins endpoints

---

api/swagger/swagger-v1.yaml

Update swagger with new creatorWalletAddress field

---

api/v1_create_coin.go
api/v1_create_coin_test.go

Revert "Undo launchpad coin is verified check (again for QA reasons)"

---

api/v1_create_coin.go
api/v1_create_coin_test.go

This will **DISABLE** the verified check
Reverts AudiusProject/api#462

DISABLE is verified check on coin creation
