solana/indexer/backfill.go
solana/indexer/backfill_test.go
solana/indexer/balance_changes.go
solana/indexer/payment_router.go
solana/indexer/processor.go
solana/indexer/processor_test.go
solana/indexer/solana_indexer.go
solana/indexer/subscription.go
solana/indexer/utils.go

Because the processor gets fired for the same transaction if multiple accounts are included from the tracked mints, it makes sense to cache these transaction responses to not abuse our RPC budget. The cache has a hit ratio of about 66%, which makes a bit of sense considering for every balance change in one account there's at least one balance change in another of the same mint.
Also fixes a bug where the mint filtering wasn't working, opting to separate the concerns and caching the retrieved artist_coins until the subscription blows away the cache.
Also:
- Fixes a bug where payment router wasn't ignoring conflicts.
- Removes batch sleep (tx sleep is enough)
- Fixes the "prod" test to use a non-JS interpreted response
- Adds a test to ensure the mint filters work

Solana Indexer: Caching

---

api/v1_users_coin.go
api/v1_users_coin_test.go

Updates `v1/users/:userId/coins/:mint` to list each individual account and account balance, per the original spec.

Update v1UsersCoin to list individual accounts

---

logging/logger.go

After reading https://github.com/uber-go/zap/issues/328 more carefully, seems like most are just ignoring sync errors entirely.

Ignore sync errors entirely

---

api/swagger/swagger-v1.yaml
api/v1_coin.go
api/v1_coin_test.go
api/v1_coins.go
api/v1_coins_test.go
api/v1_users_coin.go
api/v1_users_coin_test.go
api/v1_users_coins.go
api/v1_users_coins_test.go

Include decimals as a top level field whenever returning an artist coin, so that `FixedDecimal` on the client has something to work with.
Also updates the schema to rename `total_balance` and `total_balance_usd` to `balance` and `balance_usd`, and include the other fields returned.

Include Decimals in v1UsersCoins and others

---

ddl/migrations/0152_migrate_user_banks.sql

The "members" related queries uses data from the `sol_token_account_balance_changes` and `sol_token_account_balances` tables, as well as data from `sol_claimable_accounts`. This migration will populate data into those new tables using the existing $AUDIO specific tables like `audio_transaction_history`, `user_bank_accounts`, and `user_bank_txs`
The future history endpoint may use all of these, so figured might as well get the rest migrated now too. So this also populates data from `user_tips` to `sol_claimable_account_transfers` and `challenge_disbursements` to `sol_reward_disbursements`. In any case, this will set us up to be in parity for what the state of the world is between old and new tables regarding $AUDIO.

Populate data from $AUDIO specific tables to mint agnostic tables

---

api/birdeye/client.go
api/v1_coin.go
api/v1_coin_test.go
api/v1_coins.go
api/v1_coins_test.go
api/v1_users_coin_test.go
api/v1_users_coins_test.go

Previously, the `v1Coins` and `v1Coin` endpoints were calculating the total number of members that existed 24hrs ago. This is unnecessary. In this PR, we instead calculate how many members were added and removed in the last 24hrs, and use that to derive how many members there were 24hrs ago.
This brings the $AUDIO coin query down from 20s to 1.2s. It gets around 2.5s if missing the cache for the token overviews from birdeye, so I increased the cache time there too.
NOTE: This doesn't take into account added/removed associated wallets.

Make 24h members calculation faster

---

api/server.go
api/v1_users_purchasers.go
api/v1_users_purchasers_test.go

[API-223] Add v1/users/:userId/purchasers

---

api/birdeye/client.go

If all the token prices are cached, the birdeye client 400s because of an empty list of mints to fetch. Return early if all mints were cached to avoid this.

Fix 400 when all token prices come from cache

---

ddl/migrations/0153_fix_blocktimestamp_index.sql

Last attempt before I punt this entirely and move to SDK/solana-relay plan but i took a look at this query plan https://explain.depesz.com/s/ZGM5 and saw the seq scans that shouldn't be there... then realized that the takeaway from the "block_passed" investigation was also related to `<>` not being usable in indexes if they're in the wrong order.. and AI also confirmed this index was backwards...
So I tried it on local db w/ some prod data with 1mil+ balance changes and it seemed to really speed things up. Hoping that it works well in actual prod too.

Fix blocktimestamp index

---

api/stream_util.go
api/v1_track_stream_test.go

to test:
run `make` against prod
hit this track on the local server https://api.audius.co/v1/tracks/ryJpOa9/stream
it will still stream but with ffprobe you also get the id3 tags back

send id3 tags on all stream

---

api/server.go
api/swagger/swagger-v1.yaml
api/v1_users_addresses.go
api/v1_users_addresses_test.go

Finds user IDs associated with given addresses of wallets or accounts.
This not only enables the Discord bot to do signature recovery and find the relevant account without needing us to change the authentication of the v1/users/account/:wallet route, but also allows for more general user locating based on associated addresses by any means besides just their account wallet, which opens the door to doing "1-click purchase" if a user buys with a connected wallet on a third party site, etc.
TODO:

Add v1/users/address to find user IDs by associated wallet or account addresses

---

api/v1_track_comment_count.go
api/v1_track_comments.go

1. prior implementation from @stereosteve missed the muted stuff entirely... that is fixed (borrowing from the counts query)
2. add filtering for low scores (see commit 270c414c8505b53ea460b6d1fcc54acab456f2b7)
Tested =
need more tests, but manually hit this endpoint and spot checked results
http://localhost:1323/v1/tracks/1Yyzb0W/comments?limit=100

Filter bad comments

---

api/swagger/swagger-v1-full.yaml
api/v1_notifications.go
api/v1_notifications_test.go

Commits can be reviewed separately if you'd like.
3 Changes:
1. Fix bug in seen_at grouping from previous implementation in https://github.com/AudiusProject/api/pull/287. Currently with the checked in code, we are not grouping unread messages. Add some comments in the sql to make this more obvious to future readers
2. Always return all notification types (change the param from validTypes to types in future to prevent regression). Protocol PR here: https://github.com/AudiusProject/audius-protocol/pull/12669
3. Filter out notifications for deleted tracks / playlists (API-135) from a few months ago, which we said we could patch in the new bridge impl when that shipped.

[API-135] Fix various notification issues

---

api/v1_notifications.go

`track_milestone` and `playlist_milestone` are not valid types, so remove them
`usdc_transfer` is not a frontend supported notif, so don't return it for now. ideally this is handled on the frontend and the API is able to return it
curl http://localhost:1323/v1/notifications/y8457
> no usdc_transfer notif now

Fix notification types

---

api/dbv1/models.go
api/v1_claim_rewards.go
api/v1_claim_rewards_test.go

(first commit)
Re-work fetchAttestations to be more resilient than just picking 3 nodes. Instead we (in parallel) fetch attestations for AAO, 3 nodes with unique owners, and then keep cycling if we have failure until we get 3 uniquely owned attestations.
(second commit)
This also uncovered a fun bug with the compute budget code. When the TX needs to get split into two parts, the first part already has a compute budget smaller than the full TX, which causes simulation to fail (exhausting the budget) while trying to re-calculate compute budget for the full TX. Break up the preTx into a partial & remainder and build them in parallel to prevent this situation.
Tested=
```
make
curl -X POST http://localhost:1323/v1/rewards/claim \
-H "Content-Type: application/json" \
-d '{
"challengeId": "e", …
```

[API-96] Make attestation fetching more resilient

---

.github/workflows/build.yml

#317 had a bug where the arch dependent builds weren't being pushed with tags unique to the arch when on main branch.

Fixes latest pushes to be tagged by arch

---

.github/workflows/build.yml

In main, the builds were doing both "latest" and sha-based tags on each arch image, then trying to combine all four together into the "latest" and sha-based tag for the combined manifest.
This PR splits it out so that the arch dependent builds are just sha based, and an extra metadata extraction step gets their tags instead of sharing the one for the outputs in the merge phase.

Don't use "latest" for arch dependent builds for simplicity

---

.github/workflows/build.yml

The output of the meta step produced a space delimited list of tags. One of those was being used as an _input_ due to the space. This updates this to add each as a separate tag arg.
Also reintroduces platform specific latest images.

Fix multi-tag output on main

---

api/v1_users_history.go

Default behavior of the full tracks query is to exclude unlisted items that don't belong to the current user. But this results in `null` items in the output if they listened to any unlisted tracks that don't belong to you.

Include unlisted in listening history to prevent null items in output

---

api/swagger/swagger-v1-full.yaml

The remix `track_owner_id` and cosign `parent_track_owner_id` are derived from the `specifier` on DN rather than coming from the action data. Remove these so that we can update sdk and find breaking usages, as we don't have these in the new endpoint.

Remove missing fields from notifications swagger

---

api/server.go

Currently
```
curl http://[::1]:1323
```
Doesn't work
while
```
curl http://0.0.0.0:1323
```
does
When running against sdk locally in a node env, things seem to prefer ipv6

Allow localhost IPV6 to work

---

api/dbv1/full_playlists.go
api/v1_playlists_trending.go
api/v1_playlists_trending_test.go

This restores a behavior we had on DN to limit the number of tracks fetched in the `full` logic to just the first five.
This prevents really large playlists from slowing down the response times. But it does mean playlist tiles are only going to play 5 items from the playlist unless we otherwise fetch the remaining tracks on client.
Chatted with @dylanjeffers about this and it's a reasonable trade off for now.

[API-205][QA-2309] Limit trending playlists track fetching to 5 items

---

api/comms/chat.go
api/comms/chat_blast.go
api/comms/chat_blast_test.go
api/comms/chat_block_test.go
api/comms/chat_create_test.go
api/comms/chat_delete_test.go
api/comms/chat_permissions_test.go
api/comms/chat_test.go
api/comms/chat_test_queries.go
api/comms/rate_limit_test.go
api/comms_mutate_test.go
api/dbv1/chat_messages_row.go
solana/indexer/db_insert_test.go

This is a followup to #338 to migrate the quite sizable blasts test file. Source is here: https://github.com/AudiusProject/audius-protocol/blob/ab73d979f98e151ac0aa408c7a82c105c3b6355e/comms/discovery/rpcz/chat_blast_test.go#L760
* Migrated everything to pgx patterns
* Split the file into multiple isolated tests instead of one huge test
* Using fixtures instead of manual inserts for setup data
* Removed a lot of the 'in the past' time variables in favor of just using time.Now() for operations that are sequential
* Updated the version of `getNewBlasts` in the comms directory to match the one we use in the get endpoint. We are being intentionally WET here.
* Fixed an issue with upgrading blasts to chats where the timestamp that we assign to the new message would be in the wrong timezone if …

[API-321] Migrate tests for blast writes

---

api/swagger/swagger-v1.yaml
api/v1_coin.go
api/v1_coins.go
ddl/migrations/0157_artist_coin_names.sql
sql/01_schema.sql

- Adds `name` to coins in the db
- Allows searching by name or ticker using the `query` query parameter on the `/coins` endpoint

Search query for /coins, add name to coin

---

api/server.go
api/swagger/swagger-v1.yaml
api/v1_coin.go
api/v1_coin_test.go

Currently, we use the `getCoin` endpoint for asset pages, but we go based off of mint. Creating a new endpoint so we can use ticker and avoid any convoluted FE logic to replace mint with ticker.  This will essentially allow us to navigate to audius.co/coins/$AUDIO. The rest of the endpoints are ok with just being mint based.
https://audius-internal.slack.com/archives/C08JHQH11R8/p1757016195240729

[PE-6613] Add `/coins/ticker/:ticker` in order to enable asset pages to use ticker 

---

api/server.go

Something is wrong with our k8s layer proxies preventing unique metrics from tracking correctly. Add ip to log statements to debug

Add ip to log statements

---

api/dbv1/get_users.sql.go
api/dbv1/queries/get_users.sql
api/v1_user_test.go

Little change to the user SQL to ignore coins with zero balances + added some explicit tests for the coins logic around user badges, since it's now getting a little complicated.

Don't return badges for zero balance coins

---

api/dbv1/models.go
api/server.go
api/v1_metrics_total_artists.go
api/v1_metrics_total_artists_test.go
api/v1_metrics_total_plays.go
api/v1_metrics_total_plays_test.go
api/v1_metrics_total_wallets.go
api/v1_metrics_total_wallets_test.go

v1/metrics/total_plays
to reach parity with discovery
add
v1/metrics/total_artists
v1/metrics/total_wallets
to support new querying behavior

Implement total_x metrics

---

api/comms_chats_messages.go
api/comms_chats_messages_test.go

Need this to show artist coin headers in artist's own outgoing blast threads.

Add audience for outgoing chat blasts

---

api/v1_create_coin.go
api/v1_create_coin_test.go
api/validator.go

Adds the following improved validations:
Enhanced Field Format Validation:
✅ Mint Address: Must be exactly 44 characters (Solana address format)
✅ Ticker Format: Must start with $ and be 2-10 characters total
✅ Ticker Characters: Only alphanumeric characters after $
✅ Name Format: Only letters, numbers, spaces, hyphens, and underscores
✅ Logo URI: Must be valid HTTP/HTTPS URL (if provided)
Additional Security Validations:
✅ Name Length: Minimum 1 character (not empty)
✅ Logo URI Length: Maximum 500 characters (if provided)
✅ Character Validation: Prevents injection of special characters

[PE-6793] Create coin validation

---

api/dbv1/access.go

Updated to fix the issue with the min amount calculation.
I don't know an easy way to test this, but this looks like a pretty chill change

[PE-6997] Update track access token gate check to use token decimals

---

api/v1_coin_insights.go
api/v1_coins.go

Goal is to show "artist earnings" on the UI (aka accumulated fees).
My understanding is that this "quote fee" is the field that I want

[PE-6943] Add creator quote fee to insights endpoint

---

Makefile
README.md
api/health_check.go
indexer/indexer.go
sql/01_schema.sql

This mimics the health check strategy we used for block diffs before: Pass a query param to indicate max allowed and we return a 500 if it is exceeded. Also will return 500 if we failed to compute the block diff and a max was provided.
Otherwise, this is intended to not interrupt the health check since that's also used by various consumers to get the list of content nodes.
I'm open to making this thing cache the block diff and only compute it once every few seconds if we think the RPS to this endpoint will add too much load. It does make a RPC call to core and a database request, so it's not exactly the lightest weight thing.

[API-355] Add health check metrics for new core indexer

---

api/v1_coin.go
api/v1_users_coin.go
api/v1_users_coins.go

Because the artist coin is missing stats after creation until the stats job runs (on a 5min interval right now) we should use a left join so that it still shows up when insights are missing. The insights are used in the query for getting price, as is the pool, so we'll have to do some extra work here I think to prevent the price from looking like 0?
Testing this locally was a bit of a beast... I think we just get this out and test against prod launch of a coin to see if this solves the optimism problem since none of this is live yet anyway.

Fix missing coin balance after creation

---

api/v1_create_coin.go
jobs/coin_dbc.go

Improves on https://github.com/AudiusProject/api/commit/d69f8e6e881537a4734dd2990592e63f514da937
* Create separate function to update just one mint's dbc
* Polls for mint to return before returning success
Tested:
* Pointed client against localhost:1323
* Created a coin (spinner took a few seconds longer)
* Immediately upon response, coin data existed in `artist_coin_pools` table, and returned from API

[PE-7049] Fetch dbc data and block until it comes back in coin post

---

jobs/coin_dbc.go
solana/indexer/fake_rpc_client/fake_rpc_client.go
solana/indexer/solana_indexer.go
solana/indexer/subscription.go
solana/indexer/subscription_test.go
solana/spl/programs/meteora_dbc/client.go
solana/spl/programs/meteora_dbc/pool.go
solana/spl/programs/meteora_dbc/state.go

The RPC doesn't always have the state change by the time the subscription notifies the indexer, causing the DBC to not be found.
The subscription actually gives us the updated state, so use that instead.
Still need to fetch the config, but that's going to be stable and around much longer and won't change as frequently.

Update dbc pools without needing RPC

---

solana/indexer/subscription.go

Limits the amount of retracing when the subscriptions are changed so that we don't accidentally fall too far behind.

Only go back 100 slots when new coins are added

---

api/comms/rpc_processor.go

Bug: if a fan receives an artist coin blast during an ongoing session, it will not have the artist coin header.
Solution: append it to the outgoing message RPC.
This had actually been implemented in the old comms codebase, but we forgot it when we migrated writes to api.
Tested by pointing local api against stage and sending artist coin blasts.

Fix in-session blasts not showing artist coin header
